name: quizly
description: An application aimed at conducting customisable quizzes to its users.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # External dependencies
  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  uuid: ^2.0.4
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  http: ^0.12.1
  flutter_spinkit: ^4.1.2+1
  html_unescape: ^1.0.1+3
  flutter_svg: ^0.17.4
  super_hero: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
